import {identity,input,respond,guarded,db,now,publicBooking} from '@/lib/server';
import {bookingConfigs} from '@/lib/booking';
import {bookingIntervals} from '@/lib/request-validation';
import {z} from 'zod';
import {legacyProductEnabled} from '@/config/site';
import {createServerId} from '@/lib/ids';
const profile=z.object({name:z.string().trim().min(3).max(100),service:z.string(),district:z.string().trim().min(3).max(150),credentials:z.string().trim().min(4).max(300),bio:z.string().trim().min(20).max(1000)});
export async function GET(){if(!legacyProductEnabled())return respond({error:'NOT_AVAILABLE'},404);return guarded(async()=>{const u=await identity();if(!u)return respond({error:'AUTH_REQUIRED'},401);const p=await db().prepare('SELECT * FROM professionals WHERE user_id=?').bind(u.id).first<any>();if(!p)return respond({profile:null,requests:[]});const rows=await db().prepare("SELECT b.*,p.name AS provider_name FROM bookings b LEFT JOIN professionals p ON p.id=b.provider_id WHERE b.provider_id=? OR (b.status='requested' AND b.service=? AND ?='approved') ORDER BY b.created_at DESC LIMIT 100").bind(p.id,p.service,p.status).all<any>();return respond({profile:p,requests:rows.results.map((b:any)=>{const view=publicBooking(b);if(b.provider_id!==p.id){delete view.email;delete view.user_id;view.data={...view.data,phone:undefined,address:undefined}}return view})})})}
export async function POST(req:Request){if(!legacyProductEnabled())return respond({error:'NOT_AVAILABLE'},404);return guarded(async()=>{const u=await identity();if(!u)return respond({error:'AUTH_REQUIRED'},401);const parsed=profile.safeParse(await input(req));if(!parsed.success||!bookingConfigs.some(c=>c.slug===parsed.data.service))return respond({error:'FIELDS'},422);const d=parsed.data;await db().prepare("INSERT INTO professionals(id,user_id,email,name,service,district,credentials,bio,status,created_at) VALUES(?,?,?,?,?,?,?,?,'pending',?) ON CONFLICT(user_id) DO NOTHING").bind(createServerId(),u.id,u.email,d.name,d.service,d.district,d.credentials,d.bio,now()).run();return respond({ok:true})})}
export async function PATCH(req:Request){if(!legacyProductEnabled())return respond({error:'NOT_AVAILABLE'},404);return guarded(async()=>{const u=await identity();if(!u)return respond({error:'AUTH_REQUIRED'},401);const p=await db().prepare("SELECT * FROM professionals WHERE user_id=? AND status='approved'").bind(u.id).first<any>();if(!p)return respond({error:'APPROVAL_REQUIRED'},403);const body=await input(req);
 const offer=z.object({id:z.string().uuid(),amount:z.number().int().min(100000).max(1000000000),terms:z.string().trim().min(20).max(2000)}).safeParse(body);if(!offer.success)return respond({error:'FIELDS'},422);const d=offer.data;const b=await db().prepare("SELECT * FROM bookings WHERE id=? AND service=? AND status IN ('requested','quoted')").bind(d.id,p.service).first<any>();if(!b||b.status==='quoted'&&b.offer_expires>now())return respond({error:'UNAVAILABLE'},409);const request=JSON.parse(b.data);const intervals=bookingIntervals(request);if(intervals.some(i=>i.start<=now()))return respond({error:'DATE_PASSED'},409);const expires=Math.min(now()+86400,intervals[0].start-3600);if(expires<=now())return respond({error:'DATE_PASSED'},409);
 const actions=[db().prepare("UPDATE bookings SET status='quoted',provider_id=?,amount=?,terms=?,offer_expires=?,payment_ref=NULL,updated_at=? WHERE id=? AND (status='requested' OR (status='quoted' AND offer_expires<?))").bind(p.id,d.amount,d.terms,expires,now(),b.id,now()),db().prepare('DELETE FROM holds WHERE booking_id=? AND expires<=?').bind(b.id,now()),...intervals.map(i=>db().prepare('INSERT INTO holds(id,booking_id,provider_id,starts,ends,expires) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=? AND provider_id=? AND offer_expires=?)').bind(createServerId(),b.id,p.id,i.start,i.end,expires,b.id,p.id,expires))];
 try{const result=await db().batch(actions);if(!result[0].meta.changes)return respond({error:'UNAVAILABLE'},409)}catch{return respond({error:'SCHEDULE_CONFLICT'},409)}return respond({ok:true})})}
