import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {createHash} from 'node:crypto';
import {request,env} from './test-runtime.mjs';
const secret='prod_events_TEST_ONLY',key='pub_prod_TEST_ONLY';
Object.assign(env,{WOMPI_EVENTS_SECRET:secret,WOMPI_PUBLIC_KEY:key,WOMPI_INTEGRITY_SECRET:'prod_integrity_TEST_ONLY'});
const seconds=()=>Math.floor(Date.now()/1000);
function seed(id,status='quoted'){const s=seconds();env.DB.sqlite.prepare('INSERT INTO bookings(id,user_id,email,idempotency_key,service,data,status,provider_id,amount,terms,offer_expires,payment_ref,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'buyer','buyer@example.test',randomUUID(),'veterinario-online-colombia',JSON.stringify({lang:'es'}),status,'pro',5000000,'Test offer',s+3600,'REF-'+id,s,s);env.DB.sqlite.prepare('INSERT INTO holds VALUES(?,?,?,?,?,?)').run(randomUUID(),id,'pro-'+id,s+7200,s+9000,s+3600)}
function event(id,status='APPROVED'){const e={event:'transaction.updated',environment:'prod',timestamp:seconds(),data:{transaction:{id:'TX-'+id,status,amount_in_cents:5000000}},signature:{properties:['transaction.id','transaction.status','transaction.amount_in_cents'],checksum:''}};e.signature.checksum=createHash('sha256').update(e.data.transaction.id+status+'5000000'+e.timestamp+secret).digest('hex');return e}
function transaction(id,extra={}){return {id:'TX-'+id,reference:'REF-'+id,status:'APPROVED',amount_in_cents:5000000,currency:'COP',merchant:{public_key:key},...extra}}
const originalFetch=globalThis.fetch;
async function notify(id,{payload=event(id),remote=transaction(id)}={}){globalThis.fetch=async()=>Response.json({data:remote});try{return await request('/api/wompi',{method:'POST',body:payload})}finally{globalThis.fetch=originalFetch}}
const row=id=>env.DB.sqlite.prepare('SELECT * FROM bookings WHERE id=?').get(id);
test('Checkout signs immutable server amount and returns to booking list',async()=>{seed('checkout');const r=await request('/api/checkout',{user:'buyer',method:'POST',body:{id:'checkout',amount:1}});assert.equal(r.status,200);const url=new URL((await r.json()).url);assert.equal(url.origin,'https://checkout.wompi.co');assert.equal(url.searchParams.get('amount-in-cents'),'5000000');const expected=createHash('sha256').update('REF-checkout5000000COP'+url.searchParams.get('expiration-time')+env.WOMPI_INTEGRITY_SECRET).digest('hex');assert.equal(url.searchParams.get('signature:integrity'),expected);assert.equal(row('checkout').status,'payment_pending')});
test('Forged event is rejected without confirming booking',async()=>{seed('forged');const payload=event('forged');payload.signature.checksum='0'.repeat(64);assert.equal((await notify('forged',{payload})).status,401);assert.equal(row('forged').status,'quoted')});
test('Wrong currency or amount cannot confirm appointment',async()=>{seed('wrong');assert.equal((await notify('wrong',{remote:transaction('wrong',{currency:'USD'})})).status,422);assert.equal((await notify('wrong',{remote:transaction('wrong',{amount_in_cents:1})})).status,422);assert.equal(row('wrong').paid_at,null)});
test('Verified approval confirms once, duplicate and stale decline cannot downgrade',async()=>{seed('good','payment_pending');assert.equal((await notify('good')).status,200);assert.equal(row('good').status,'confirmed');const paid=row('good').paid_at;assert.equal((await notify('good')).status,200);assert.equal((await notify('good',{payload:event('good','DECLINED'),remote:transaction('good',{status:'DECLINED'})})).status,200);assert.equal(row('good').paid_at,paid);assert.equal(row('good').status,'confirmed')});
test('Late approval with expired slot goes to review, never double books',async()=>{seed('late','payment_pending');env.DB.sqlite.prepare('UPDATE holds SET expires=? WHERE booking_id=?').run(seconds()-1,'late');assert.equal((await notify('late')).status,200);assert.equal(row('late').status,'paid_attention')});
test('Cancellation during payment followed by approval needs refund review',async()=>{seed('cancel','payment_pending');assert.equal((await request('/api/bookings/cancel',{user:'buyer',method:'PATCH',body:{action:'cancel'}})).status,200);assert.equal(row('cancel').status,'cancel_requested');assert.equal((await notify('cancel')).status,200);assert.equal(row('cancel').status,'refund_requested')});
test('Decline frees payment attempt for a retry, does not mark paid',async()=>{seed('decline','payment_pending');assert.equal((await notify('decline',{payload:event('decline','DECLINED'),remote:transaction('decline',{status:'DECLINED'})})).status,200);assert.equal(row('decline').paid_at,null);assert.equal(row('decline').status,'quoted');assert.equal(row('decline').payment_ref,null)});
test('Concurrent checkout clicks keep one payment reference',async()=>{seed('parallel');env.DB.sqlite.prepare('UPDATE bookings SET payment_ref=NULL WHERE id=?').run('parallel');const results=await Promise.all([request('/api/checkout',{user:'buyer',method:'POST',body:{id:'parallel'}}),request('/api/checkout',{user:'buyer',method:'POST',body:{id:'parallel'}})]);const urls=await Promise.all(results.map(async r=>{assert.equal(r.status,200);return new URL((await r.json()).url)}));assert.equal(urls[0].searchParams.get('reference'),urls[1].searchParams.get('reference'))});
