import {notFound} from 'next/navigation';
import {ArrowRight,Check} from 'lucide-react';
import SiteShell from './site-shell';
import HomePage from './chomby-home';
import BookingFlow from './booking-flow';
import AuthGate from './auth-gate';
import AccountPanel from './account-panel';
import {Lang,catalog,route,faq,optionMode} from '@/lib/catalog';
import {colombiaToday} from '@/lib/booking';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {admin} from '@/lib/server';
import {metadataFor,jsonLd,pageGraph} from '@/lib/seo';
const names=(lang:Lang)=>lang==='en'?{home:'Online veterinarians and pet services in Bogotá',about:'About Chombly',pro:'Pet care professionals in Bogotá',bookings:'My bookings',privacy:'How Chombly uses your data'}:{home:'Veterinarios online y servicios para mascotas en Bogotá',about:'Sobre Chombly',pro:'Profesionales del cuidado animal en Bogotá',bookings:'Mis reservas',privacy:'Cómo usa Chombly tus datos'};
export function pageMetadata(path:string,lang:Lang){const n=names(lang),c=catalog(lang).find(c=>path.endsWith('/'+c.slug));const title=c?c.title+' · Bogotá':path==='/'?n.home:path==='/sobre-chomby'?n.about:path==='/profesionales'?n.pro:path==='/privacidad'?n.privacy:n.bookings;const description=c?.description||(lang==='en'?'Explore veterinary care, grooming, dog walking, pet hotels, daycare and training in Bogotá. Request an appointment and review the final price before payment.':'Explora veterinarios, peluquería, paseos, hoteles, guardería y entrenamiento en Bogotá. Solicita una cita y revisa el precio final antes de pagar.');return metadataFor(title,description,route(path,lang),lang)}
export async function RenderPage({path,lang}:{path:string,lang:Lang}){const en=lang==='en';if(path==='/')return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(pageGraph(route('/',lang),names(lang).home,String(pageMetadata('/',lang).description),faq(lang),lang))}}/><HomePage lang={lang}/></>;
 const match=path.match(/^\/(servicios|agendar)\/([^/]+)$/);if(match){const c=catalog(lang).find(c=>c.slug===match[2]);if(!c)notFound();if(match[1]==='agendar'){const user=await getChatGPTUser();return <SiteShell lang={lang} path={path}>{user?<BookingFlow slug={c.slug} lang={lang} today={colombiaToday()} email={user.email}/>:<AuthGate lang={lang} path={route(path,lang)} title={c.title}/>}</SiteShell>}
 return <SiteShell lang={lang} path={path}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(pageGraph(route(path,lang),c.title,c.description,faq(lang),lang))}}/><section className="shell service-hero photo-detail"><div><p className="eyebrow">BOGOTÁ, COLOMBIA</p><h1>{c.title}</h1><p className="service-intro">{c.description}</p><p>{en?'Send your preferred dates and needs. Before paying, review the professional’s offer, exact time, final total and cancellation conditions.':'Envía tus fechas preferidas y necesidades. Antes de pagar, revisa la propuesta del profesional, el horario exacto, el total final y las condiciones de cancelación.'}</p><a className="button" href={route('/agendar/'+c.slug,lang)}>{en?'Request this service':'Solicitar este servicio'}<ArrowRight size={18}/></a></div><img src={c.image} width="1536" height="1024" alt={c.title} fetchPriority="high"/></section><section className="shell service-detail-options"><h2>{en?'Choose the care you need':'Elige el cuidado que necesitas'}</h2><div>{c.options.map(o=><article key={o.id}><Check size={22}/><h3>{o.label}</h3><p>{optionMode(o.mode,lang)}</p></article>)}</div><div className="detail-notes"><section><h2>{en?'Price and availability':'Precio y disponibilidad'}</h2><p>{c.kind==='vet'?(en?'US$10 is a provisional reference. The final total in COP must be confirmed in the offer. No charge is made when you send a request.':'US$10 es una referencia provisional. El total final en COP debe confirmarse en la propuesta. No se cobra al enviar una solicitud.'):(en?'The professional quotes the final total based on your animal, service and dates. No price is invented or charged before you review the offer.':'El profesional cotiza el total final según tu animal, servicio y fechas. El precio no se cobra antes de que revises la propuesta.')}</p></section><section><h2>{en?'Bogotá coverage':'Cobertura en Bogotá'}</h2><p>{en?'Select your locality when requesting. A listed locality does not guarantee an active professional; the professional must confirm coverage.':'Selecciona tu localidad al solicitar. Que una localidad aparezca no garantiza un profesional activo; el profesional debe confirmar la cobertura.'}</p></section></div>{c.kind==='vet'&&<p className="medical-note">{en?'Online consultation does not replace emergency care or every physical examination. Diagnosis and prescriptions depend on the veterinarian’s assessment.':'La consulta online no sustituye las urgencias ni todas las exploraciones presenciales. El diagnóstico y las fórmulas dependen de la valoración veterinaria.'}</p>}<div className="faq-list">{faq(lang).map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section></SiteShell>}
 if(['/mis-reservas','/profesionales','/administracion'].includes(path)){const u=await getChatGPTUser();const mode=path==='/mis-reservas'?'customer':path==='/profesionales'?'professional':'admin';if(mode==='admin'&&u&&!admin(u.email))notFound();return <SiteShell lang={lang} path={path}>{u?<AccountPanel lang={lang} mode={mode} email={u.email}/>:<AuthGate lang={lang} path={route(path,lang)} title={mode==='professional'?names(lang).pro:mode==='admin'?(en?'Administration':'Administración'):names(lang).bookings}/>}</SiteShell>}
 if(path==='/sobre-chomby')return <SiteShell lang={lang} path={path}><article className="shell information-page"><p className="eyebrow">CHOMBLY · COLOMBIA</p><h1>{en?'Care should feel closer.':'El cuidado debería sentirse más cerca.'}</h1><p className="direct-answer">{en?'Chombly starts with a simple need: many people have questions about their animals and do not know which professional to ask. We want to bring veterinary guidance and everyday pet services closer, starting in Bogotá.':'Chombly nace de una necesidad sencilla: muchas personas tienen preguntas sobre sus animales y no saben a qué profesional acudir. Queremos acercar la orientación veterinaria y los cuidados de todos los días, empezando en Bogotá.'}</p><section className="content-section"><h2>{en?'Six services, one place':'Seis servicios, un solo lugar'}</h2><p>{en?'Veterinary consultations, grooming, walks, hotels, daycare and training. Each service has its own request flow; the professional confirms coverage, availability and price.':'Consultas veterinarias, peluquería, paseos, hoteles, guardería y entrenamiento. Cada servicio tiene su propio recorrido de solicitud; el profesional confirma cobertura, disponibilidad y precio.'}</p></section><section className="content-section"><h2>{en?'A launch in preparation':'Un lanzamiento en preparación'}</h2><p>{en?'We are preparing the professional network and payment setup. We do not claim round-the-clock availability or confirmed appointments without a professional and verified payment.':'Estamos preparando la red de profesionales y la conexión de pagos. No prometemos disponibilidad las 24 horas ni citas confirmadas sin un profesional y un pago verificado.'}</p></section><a className="button" href={route('/#servicios',lang)}>{en?'Explore services':'Explorar servicios'}<ArrowRight size={18}/></a></article></SiteShell>;
 if(path==='/privacidad')return <SiteShell lang={lang} path={path}><article className="shell information-page"><h1>{names(lang).privacy}</h1><p className="direct-answer">{en?'This page explains the data used by the current booking flow. The final business identity, contact channel, retention periods and full privacy terms must be completed before commercial launch.':'Esta página explica los datos que utiliza el recorrido actual de reservas. La identidad legal del negocio, el canal de contacto, los plazos de conservación y la política completa deben completarse antes del lanzamiento comercial.'}</p>{(en?[
 ['What is saved','Your sign-in identifier and email, animal details, preferred dates, Bogotá locality, contact phone, service needs and address only when home service requires it. Professional applications also store the information entered for credential review.'],
 ['Why it is used','To save and manage your request, find a suitable professional, show an offer and track payment and cancellation status. This flow does not subscribe you to marketing.'],
 ['Who can see it','Your bookings are linked to your account. Approved professionals in the requested category may review animal needs, dates and locality. Your address and phone are shared with the professional handling your request. Chombly administrators can manage applications and booking issues.'],
 ['Payments and help chat','Card details are entered on Wompi checkout, not stored in Chombly. The help chat runs with platform help information; messages are not saved in the booking database.'],
 ['Before launch','The business must establish a verified contact channel for data access, correction and deletion requests and publish its complete privacy and service policies.']
 ]:[['Qué se guarda','Tu identificador de acceso y correo, datos del animal, fechas preferidas, localidad de Bogotá, teléfono, necesidades del servicio y dirección solo cuando la atención a domicilio lo requiere. Las solicitudes profesionales guardan además la información para revisar credenciales.'],['Para qué se usa','Para guardar y gestionar tu solicitud, encontrar un profesional adecuado, mostrar una propuesta y seguir el estado del pago y las cancelaciones. Este recorrido no te suscribe a publicidad.'],['Quién puede verlo','Tus reservas quedan asociadas a tu cuenta. Los profesionales aprobados de la categoría solicitada pueden revisar necesidades del animal, fechas y localidad. La dirección y el teléfono se comparten con el profesional que atiende tu solicitud. La administración de Chombly puede gestionar las solicitudes y las incidencias.'],['Pagos y chat de ayuda','Los datos de tarjeta se introducen en el pago de Wompi y no se guardan en Chombly. El chat funciona con información de ayuda de la plataforma; sus mensajes no se guardan en la base de reservas.'],['Antes del lanzamiento','El negocio debe establecer un canal de contacto verificado para solicitudes de acceso, corrección y eliminación de datos, y publicar sus políticas completas de privacidad y servicio.']]).map(([h,p])=><section className="content-section" key={h}><h2>{h}</h2><p>{p}</p></section>)}</article></SiteShell>;notFound()}
