export type BookingKind="vet"|"grooming"|"walking"|"hotel"|"daycare"|"training";
export type ServiceOption={id:string;label:string;minutes:number;mode:string};
export type BookingConfig={slug:string;kind:BookingKind;title:string;animalTypes:string[];options:ServiceOption[];question:string;placeholder:string;requirements:string[]};
export const bookingConfigs:BookingConfig[]=[
 {slug:"veterinario-online-colombia",kind:"vet",title:"Consulta veterinaria online",animalTypes:["Perro","Gato","Ave","Pequeño mamífero","Otro animal"],options:[{id:"general",label:"Consulta veterinaria virtual",minutes:30,mode:"Videollamada"}],question:"¿Qué te gustaría consultar?",placeholder:"Describe el motivo de consulta con un ejemplo.",requirements:["Conexión a internet, cámara y micrófono.","Profesional con experiencia en la especie seleccionada.","La fórmula médica depende de la valoración del veterinario."]},
 {slug:"peluqueria-canina-y-felina",kind:"grooming",title:"Baño y peluquería",animalTypes:["Perro","Gato"],options:[{id:"bath",label:"Baño y cepillado",minutes:60,mode:"En establecimiento"},{id:"groom",label:"Baño y corte de pelo",minutes:90,mode:"En establecimiento"},{id:"nails",label:"Corte de uñas",minutes:30,mode:"En establecimiento"}],question:"Necesidades de pelo y manejo",placeholder:"Ej. Pelo largo, se pone nervioso con el secador.",requirements:["El profesional debe confirmar el precio según tamaño y manto.","Indica necesidades de manejo antes de la cita.","La duración mostrada es de ejemplo y puede cambiar tras la valoración."]},
 {slug:"paseadores-de-perros",kind:"walking",title:"Paseo para tu perro",animalTypes:["Perro"],options:[{id:"walk30",label:"Paseo individual · 30 minutos",minutes:30,mode:"Recogida en domicilio"},{id:"walk60",label:"Paseo individual · 60 minutos",minutes:60,mode:"Recogida en domicilio"},{id:"group",label:"Paseo grupal · 60 minutos",minutes:60,mode:"Recogida en domicilio"}],question:"Rutina y comportamiento durante el paseo",placeholder:"Ej. Se emociona al ver otros perros. Lleva arnés.",requirements:["Acordar punto de recogida y entrega.","Confirmar convivencia antes de elegir un paseo grupal.","El equipo de paseo y las instrucciones deben estar disponibles."]},
 {slug:"hotel-para-mascotas",kind:"hotel",title:"Estancia en hotel para mascotas",animalTypes:["Perro","Gato"],options:[{id:"boarding",label:"Alojamiento por noches",minutes:0,mode:"En establecimiento"}],question:"Alimentación y cuidados durante la estancia",placeholder:"Ej. Lleva su alimento, come dos veces al día.",requirements:["Confirmar requisitos de ingreso y documentos con el hotel.","Acordar alimentación, pertenencias y cuidados.","Recogida, transporte y medicamentos no se presumen incluidos."]},
 {slug:"guarderia-y-cuidadores",kind:"daycare",title:"Guardería y cuidado en casa",animalTypes:["Perro","Gato"],options:[{id:"half",label:"Guardería · media jornada (4 h)",minutes:240,mode:"En establecimiento"},{id:"full",label:"Guardería · jornada (8 h)",minutes:480,mode:"En establecimiento"},{id:"visit",label:"Visita a domicilio · 30 minutos",minutes:30,mode:"En tu domicilio"}],question:"Rutina e instrucciones de cuidado",placeholder:"Ej. Servir alimento, renovar agua y acompañarlo.",requirements:["Acordar tareas y tiempo de supervisión.","Confirmar quién entrega y recibe al animal.","Para visitas en casa, acordar acceso con el cuidador."]},
 {slug:"entrenamiento-canino",kind:"training",title:"Sesión de entrenamiento canino",animalTypes:["Perro"],options:[{id:"assessment",label:"Valoración inicial · 60 minutos",minutes:60,mode:"En establecimiento"},{id:"home",label:"Sesión individual a domicilio · 60 minutos",minutes:60,mode:"En tu domicilio"}],question:"¿Qué te gustaría trabajar?",placeholder:"Ej. Pasear con correa y mejorar la convivencia en casa.",requirements:["Acordar objetivos, método y participación de la familia.","No se garantizan resultados ni un número fijo de sesiones.","Los cambios de salud o conducta pueden requerir valoración veterinaria."]},
];
export function colombiaToday(now=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(now)}
export function validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(value+"T12:00:00Z");return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value}
export function addDays(value:string,days:number){if(!validDate(value))return "";const d=new Date(value+"T12:00:00Z");d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function nights(from:string,to:string){if(!validDate(from)||!validDate(to))return 0;return Math.round((Date.parse(to+"T12:00:00Z")-Date.parse(from+"T12:00:00Z"))/86400000)}
