export type ServiceContent = {
 slug:string; title:string; name:string; description:string; intro:string; definition:string; eyebrow:string;
 sections:{heading:string;text:string;items?:string[]}[];
 compare:{title:string;items:string[]}; price:string; coverage:string; faqs:[string,string][];
};
export const homeFaqs: [string,string][] = [
 ["¿Qué es Chomby y qué servicios tendrá en Colombia?","Chomby es una plataforma en preparación para conectar a personas con veterinarios online, peluquería para mascotas, paseadores de perros, hoteles, guardería, cuidadores y entrenamiento. El lanzamiento inicial está previsto para Colombia; la disponibilidad de cada servicio está por confirmar."],
 ["¿Cómo funciona una consulta veterinaria online?","El recorrido previsto permite elegir un veterinario y un horario, compartir información sobre el animal y entrar a una videollamada. El profesional determina qué puede atender a distancia y cuándo se necesita una valoración presencial. Por ahora, la reserva es una demostración."],
 ["¿Cuánto cuesta una consulta veterinaria virtual en Chomby?","El prototipo muestra US$10 por consulta como referencia provisional. El precio final en pesos colombianos, los medios de pago y las condiciones se confirmarán antes del lanzamiento. Esta versión no realiza cobros."],
 ["¿Se atenderán perros, gatos y otros animales?","El proyecto contempla distintos tipos de animales. La atención dependerá de la especie y de la experiencia del veterinario disponible, que deberá confirmarse antes de reservar."],
 ["¿Recibiré una fórmula médica por la consulta online?","El veterinario determina si corresponde emitir una fórmula y si el caso requiere una valoración presencial. Cuando proceda, la fórmula y las indicaciones estarán disponibles dentro de Chomby. La consulta no incluye la compra ni la entrega de medicamentos."],
 ["¿Chomby tendrá veterinarios 24 horas, consultas gratis o urgencias?","No se han confirmado horarios de atención las 24 horas ni consultas gratuitas. Chomby no ofrece atención de urgencias en este prototipo. Ante una urgencia, acude a un centro veterinario presencial."],
];
export const serviceContent: ServiceContent[] = [
 {slug:"veterinario-online-colombia",name:"Veterinarios online",title:"Veterinario online en Colombia",description:"Conoce la consulta veterinaria online de Chomby en Colombia: videollamada, precio provisional, especies, indicaciones y límites. Lanzamiento en preparación.",eyebrow:"CONSULTA VETERINARIA VIRTUAL",intro:"Habla con un profesional sobre tu animal, aunque no tengas una clínica cerca.",definition:"Una consulta veterinaria online conecta al cuidador con un veterinario por videollamada. En Chomby podrás revisar el profesional, la especie que atiende y el horario antes de reservar. El servicio se encuentra en preparación para Colombia.",sections:[
 {heading:"¿Cómo será la cita con un veterinario virtual?",text:"El recorrido está pensado para que sepas con quién hablarás y qué pasará después de la cita.",items:["Indica la especie, el nombre de tu animal y el motivo de consulta.","Elige un veterinario que atienda esa especie y revisa los horarios disponibles.","Confirma el precio y las condiciones antes del pago.","Entra a la videollamada desde la plataforma.","Consulta las indicaciones y, cuando corresponda, la fórmula emitida por el profesional."]},
 {heading:"Preguntas para consultar sobre perros, gatos y otros animales",text:"La consulta puede empezar con dudas sobre alimentación, cuidado de cachorros, vacunación, desparasitación, comportamiento o seguimiento. Si buscas ayuda porque tu perro no come, tu gato vomita o notas un cambio en tu animal, el profesional deberá evaluar si la atención a distancia es adecuada. Esta página no establece un diagnóstico ni un tratamiento.",items:["Alimentación y cuidados de perros y gatos.","Preguntas sobre vacunas y desparasitación.","Cambios de comportamiento o dudas sobre el cuidado diario.","Seguimiento e indicaciones de una atención previa.","Atención de aves u otras especies, según el profesional disponible."]},
 {heading:"Qué puede requerir atención veterinaria presencial",text:"Una videollamada no permite realizar todos los exámenes físicos ni las pruebas que un animal puede necesitar. El veterinario decidirá cuándo corresponde una valoración en una clínica. Una consulta online no debe retrasar una atención de urgencia."}
 ],compare:{title:"Qué revisar antes de reservar",items:["Nombre, matrícula y perfil del veterinario.","Experiencia con la especie de tu animal.","Horario de la cita en hora de Colombia.","Precio final, alcance, cancelaciones y seguimiento.","Conexión, cámara y acceso a los antecedentes que quieras compartir."]},price:"La referencia del prototipo es US$10 por consulta. Todavía no es una tarifa comercial definitiva: el precio en pesos colombianos y las condiciones se confirmarán antes de habilitar pagos.",coverage:"El lanzamiento está previsto para Colombia. La consulta virtual busca facilitar el acceso incluso lejos de una clínica, sujeto a conexión a internet y disponibilidad de un profesional para la especie. No se anuncia atención inmediata ni las 24 horas.",faqs:[
 ["¿Cómo agendar una consulta veterinaria online en Colombia?","En la versión operativa de Chomby podrás indicar tu animal, elegir un veterinario y un horario, revisar el precio y confirmar la cita. Actualmente puedes explorar ese recorrido con datos de ejemplo; no hay reservas reales."],
 ["¿Cuánto cuesta un veterinario online en Chomby?","El valor mostrado es US$10, provisional. El precio final de la consulta en pesos colombianos, las formas de pago y sus condiciones están pendientes de confirmación."],
 ["¿La teleorientación veterinaria es lo mismo que un diagnóstico?","La orientación ayuda a resolver preguntas y decidir el siguiente paso. No garantiza que se pueda diagnosticar a distancia. El veterinario determina el alcance de la atención y si necesita examinar presencialmente al animal."],
 ["¿Puedo obtener una receta o fórmula veterinaria online?","No se garantiza una fórmula en cada consulta. Solo el veterinario puede determinar si corresponde emitirla y si necesita una valoración presencial. Cuando proceda, Chomby permitirá consultar sus indicaciones; no incluye entrega de medicamentos."],
 ["¿Hay veterinario online gratis o disponible 24 horas?","Chomby no ha confirmado consultas gratuitas ni atención 24 horas. Los horarios y precios reales deberán estar visibles antes de reservar. El prototipo no presta atención médica."],
 ["¿Puedo consultar si vivo lejos de una veterinaria?","Ese es uno de los objetivos de Chomby: facilitar el contacto con un profesional en Colombia mediante internet. Si el caso requiere exploración, pruebas o urgencias, será necesario acudir a atención presencial."]]},
 {slug:"peluqueria-canina-y-felina",name:"Peluquería para mascotas",title:"Peluquería canina y felina en Colombia",description:"Explora la propuesta de grooming de Chomby: baño, peluquería canina y felina, precios y preguntas para elegir un profesional. Cobertura por confirmar.",eyebrow:"BAÑO, PELUQUERÍA Y GROOMING",intro:"El cuidado de su pelo también merece un profesional que lo conozca.",definition:"La peluquería canina y felina, también llamada grooming, reúne servicios de higiene y cuidado del pelo de perros y gatos. Chomby contempla conectar a las familias con profesionales de baño y peluquería según su ciudad y las necesidades del animal.",sections:[
 {heading:"Qué puede incluir un servicio de grooming",text:"Cada profesional deberá detallar su servicio. No todos los paquetes incluyen las mismas tareas, y la atención de gatos debe confirmarse por separado.",items:["Baño y secado según el servicio contratado.","Cepillado, desenredado o deslanado cuando se ofrezca.","Corte de pelo o mantenimiento del manto.","Corte de uñas si está incluido.","Atención canina o felina según experiencia del profesional."]},
 {heading:"Cómo comparar peluquerías para perros y gatos",text:"Revisa la experiencia, las condiciones del lugar, el manejo del animal y lo que incluye el precio. Comparte antes de la cita cualquier necesidad especial y pregunta cómo se gestionan los cambios de precio por el estado del pelo."},
 {heading:"¿Grooming a domicilio o en un establecimiento?",text:"La modalidad deberá aparecer en el perfil de cada proveedor. Chomby todavía no confirma peluquería a domicilio ni sedes disponibles; antes de reservar se deberá verificar el lugar, la zona y las condiciones de atención."}
 ],compare:{title:"Información útil para pedir precio",items:["Especie, tamaño y tipo de pelo.","Servicio que necesitas y estado del manto.","Experiencias previas o necesidades de manejo.","Ciudad, modalidad y posibles costos de transporte.","Qué incluye el paquete y qué se cobra aparte."]},price:"El precio de baño y peluquería se definirá por proveedor y servicio. Dependerá de factores como tamaño, pelo, tareas incluidas y modalidad. La referencia de US$10 corresponde únicamente a la consulta veterinaria provisional.",coverage:"La cobertura presencial se confirmará por ciudad y profesional en Colombia. Seleccionar una ciudad en el prototipo no significa que ya existan peluquerías disponibles.",faqs:[
 ["¿Qué significa grooming para mascotas?","Grooming es el cuidado de higiene y presentación de la mascota, como baño, cepillado y peluquería. Las tareas concretas dependen del servicio y deben confirmarse antes de contratar."],
 ["¿Cuánto cuesta el baño y la peluquería de un perro?","Chomby aún no tiene tarifas confirmadas para grooming. El proveedor deberá mostrar el precio según el tamaño, tipo y estado del pelo, servicio y modalidad."],
 ["¿Habrá peluquería para gatos?","La categoría contempla peluquería felina, pero estará sujeta a profesionales con experiencia en gatos. No se debe asumir que un proveedor de peluquería canina también los atiende."],
 ["¿Cómo encuentro una peluquería canina cerca de mí?","En la versión operativa podrás revisar proveedores por ciudad y zona. Por ahora la cobertura no está confirmada, por lo que no hay establecimientos reales para reservar."],
 ["¿El corte de uñas está incluido?","Dependerá del paquete de cada profesional. Revisa las tareas incluidas, sus condiciones y cualquier costo adicional antes de confirmar."]]},
 {slug:"paseadores-de-perros",name:"Paseadores de perros",title:"Paseadores de perros en Colombia",description:"Conoce cómo buscar paseadores de perros en Chomby: paseos individuales o grupales, horarios, precio y zona. Red local en preparación para Colombia.",eyebrow:"PASEOS Y COMPAÑÍA",intro:"Un paseo bien organizado empieza por conocer a tu perro.",definition:"Un paseador de perros acompaña al animal durante un recorrido acordado con su cuidador. En Chomby se prevé buscar paseadores por ciudad, conocer su experiencia y revisar duración, modalidad y condiciones antes de reservar.",sections:[
 {heading:"Paseos individuales y paseos grupales",text:"Un paseo individual está dedicado a un perro o a los animales acordados de una misma familia. En un paseo grupal participan varios perros. Cada proveedor deberá explicar su modalidad, cuántos animales lleva y cómo organiza el recorrido."},
 {heading:"Cómo elegir a un paseador de perros",text:"Conversar sobre la rutina y el comportamiento del animal permite acordar un servicio adecuado. Revisa la identidad y experiencia del profesional, las condiciones de entrega y recogida y el procedimiento de contacto ante un imprevisto.",items:["Duración y horario del paseo.","Paseo individual o en grupo y número de perros.","Zona y punto de recogida y entrega.","Información o reporte al finalizar.","Condiciones de cancelación y cambios por clima."]},
 {heading:"Paseos por horas y servicios recurrentes",text:"Los proveedores podrán definir opciones según su disponibilidad. La plataforma no anuncia todavía planes semanales, seguimiento GPS ni seguros incluidos. Esas características deberán confirmarse en cada perfil cuando exista la red operativa."}
 ],compare:{title:"Cuéntale al paseador",items:["Tamaño, edad y rutina del perro.","Cómo se comporta con personas y otros animales.","Equipo de paseo y cuidados indicados por su veterinario.","Horario, punto de encuentro y contacto autorizado.","Necesidad de paseo individual o compañía específica."]},price:"No hay un precio confirmado para paseadores en Chomby. La tarifa dependerá de duración, modalidad, zona y frecuencia; cada propuesta deberá mostrar el total antes de contratar.",coverage:"El servicio será local, según ciudad y zona. No hay paseadores reales conectados al prototipo ni cobertura garantizada en todo Colombia.",faqs:[
 ["¿Cuánto cobra un paseador de perros?","Chomby aún no publica una tarifa definitiva. El costo deberá especificarse por paseo o plan, con su duración, modalidad, zona y cargos adicionales si existen."],
 ["¿Cómo encuentro un paseador de perros cerca de mí?","El recorrido previsto permite elegir ciudad y revisar la zona atendida por cada profesional. La disponibilidad deberá confirmarse antes de reservar."],
 ["¿Podré contratar paseos individuales?","Se contempla mostrar la modalidad de cada proveedor. La disponibilidad de paseos individuales o grupales se confirmará cuando la red de profesionales esté activa."],
 ["¿El paseo incluye seguimiento en tiempo real?","No se ha confirmado seguimiento GPS en Chomby. Revisa qué comunicación o reporte incluye cada servicio; no debe asumirse una función que el perfil no anuncie."],
 ["¿Puedo dejar instrucciones para mi perro?","La propuesta contempla compartir información relevante sobre el animal. Antes de contratar, el profesional deberá confirmar que puede cumplir las instrucciones y necesidades acordadas."]]},
 {slug:"hotel-para-mascotas",name:"Hoteles para mascotas",title:"Hotel para perros y gatos en Colombia",description:"Explora hoteles y alojamiento para mascotas con Chomby: estancias, requisitos, precios y cuidado de perros y gatos. Disponibilidad local por confirmar.",eyebrow:"ALOJAMIENTO PARA MASCOTAS",intro:"Cuando tú viajas, su cuidado sigue siendo lo primero.",definition:"Un hotel para mascotas ofrece alojamiento durante una o varias noches. Chomby contempla reunir opciones de hotel para perros, alojamiento para gatos y hospedaje con cuidadores, según los profesionales disponibles en cada ciudad.",sections:[
 {heading:"Hotel para perros, gatos o alojamiento en casa",text:"Los espacios y modalidades pueden variar. Un hotel canino no necesariamente recibe gatos y un alojamiento en casa no ofrece las mismas instalaciones que un establecimiento. El perfil deberá explicar qué animales atiende y cómo organiza la estancia."},
 {heading:"Qué revisar antes de dejar a tu mascota",text:"Conoce dónde dormirá, quién la atenderá y cómo se manejarán sus rutinas. Pide información sobre convivencia con otros animales, horarios de supervisión, comunicación y atención ante un imprevisto.",items:["Lugar y condiciones del alojamiento.","Especies admitidas y separación de espacios.","Requisitos de ingreso y documentación solicitada.","Alimentación, rutina y pertenencias permitidas.","Supervisión, reportes y contacto durante la estancia."]},
 {heading:"Diferencia entre hotel y guardería canina",text:"El hotel incluye una estancia nocturna. La guardería suele atender durante el día y termina con la recogida del animal. Si necesitas compañía por unas horas o mientras trabajas, revisa también la categoría de guardería y cuidadores."}
 ],compare:{title:"Prepara tu consulta de alojamiento",items:["Fechas y horarios de ingreso y salida.","Especie, tamaño y convivencia con otros animales.","Alimento y rutina del animal.","Cuidados específicos e indicaciones veterinarias.","Precio por noche, extras y política de cancelación."]},price:"Los precios de hotel para mascotas no están definidos en Chomby. Cada proveedor deberá indicar la tarifa por noche o estancia y aclarar alimentación, transporte, temporadas y otros cargos.",coverage:"El alojamiento dependerá de la ubicación y disponibilidad del proveedor en Colombia. El prototipo no ofrece cupos reales, reservas para vacaciones ni una red de hoteles confirmada.",faqs:[
 ["¿Cuánto cuesta un hotel para perros por noche?","La tarifa dependerá del proveedor, tipo de alojamiento, fechas y servicios incluidos. Chomby todavía no confirma precios ni cupos de hotel."],
 ["¿Habrá hotel para gatos?","La categoría contempla alojamiento felino sujeto a proveedores adecuados. Antes de reservar será necesario confirmar que el lugar recibe gatos y conocer sus espacios y manejo."],
 ["¿Qué requisitos piden para hospedar una mascota?","Cada establecimiento definirá sus requisitos de ingreso y documentación. Deben revisarse antes de reservar, incluyendo la información de salud que solicite el proveedor."],
 ["¿El hospedaje incluye comida y transporte?","No debe asumirse. El perfil y la cotización deberán detallar si se incluyen alimento, recogida, entrega u otros servicios y cuánto cuestan."],
 ["¿Hotel y guardería para perros son lo mismo?","No. El hotel contempla pernoctación, mientras que la guardería suele cubrir el día. Verifica el horario y modalidad para contratar el cuidado que necesitas."]]},
 {slug:"guarderia-y-cuidadores",name:"Guardería y cuidadores",title:"Guardería y cuidadores de mascotas en Colombia",description:"Conoce la propuesta de guardería canina y cuidadores a domicilio de Chomby: cuidado por horas, visitas y diferencias con el hotel. Red en preparación.",eyebrow:"CUIDADO DURANTE EL DÍA",intro:"Compañía para tu animal cuando tú necesitas ocuparte de otras cosas.",definition:"La guardería para mascotas ofrece cuidado durante el día; un cuidador también puede prestar visitas o acompañamiento en casa según su servicio. Chomby contempla ambas modalidades para buscar atención por ciudad y necesidad.",sections:[
 {heading:"Guardería canina o cuidador en casa",text:"Una guardería recibe al animal en un espacio de atención. Un cuidador a domicilio realiza visitas o estancias en el hogar según lo contratado. Cada modalidad debe explicar horarios, actividades, supervisión y condiciones de acceso."},
 {heading:"Cuidado de perros y gatos por horas",text:"La especie, rutina y convivencia son importantes al elegir el servicio. Para gatos, pregunta si se ofrecen visitas en casa y qué tareas incluye cada visita. Para perros, revisa el tiempo de compañía, salidas y actividades acordadas.",items:["Visitas para compañía, alimento o agua según el servicio.","Cuidado diurno en guardería cuando esté disponible.","Acompañamiento en casa según zona y horario.","Comunicación con el cuidador y resumen de la atención."]},
 {heading:"Acuerdos antes de entregar el cuidado",text:"Define quién recibe y entrega al animal, qué espacios puede usar el cuidador y cómo se autoriza cualquier cambio. Si hay cuidados médicos, deben comunicarse las indicaciones del veterinario y confirmar si el profesional puede cumplirlas."}
 ],compare:{title:"Qué acordar con el cuidador",items:["Duración, frecuencia y tareas de cada visita.","Rutina, alimentación y necesidades del animal.","Contacto y autorización ante imprevistos.","Recogida, entrega y acceso a la vivienda si aplica.","Tarifa total, cancelación y reporte de la atención."]},price:"Las tarifas de guardería y cuidadores están pendientes. Se deberán indicar por hora, visita, jornada o plan, con el alcance y los posibles cargos adicionales.",coverage:"Las visitas y guarderías estarán sujetas a proveedores, horarios y zonas confirmadas en Colombia. No hay cuidadores reales disponibles para contratar desde este prototipo.",faqs:[
 ["¿Cuál es la diferencia entre guardería y hotel para perros?","La guardería normalmente cubre unas horas o la jornada diurna; el hotel incluye la noche. Confirma siempre los horarios y las condiciones de recogida."],
 ["¿Puedo buscar un cuidador de gatos a domicilio?","La propuesta contempla cuidadores y visitas en casa, sujetos a profesionales y cobertura local. Deberás confirmar experiencia con gatos y qué tareas incluye la visita."],
 ["¿Cuánto cuesta una guardería canina por día?","Chomby no tiene una tarifa diaria confirmada. Cada proveedor deberá publicar su precio, horario, actividades y cargos adicionales antes de aceptar una reserva."],
 ["¿Podré contratar cuidado de mascotas por horas?","Se contempla mostrar opciones por horas, visitas o jornadas según el proveedor. La disponibilidad y duración real del servicio están por confirmar."],
 ["¿El cuidador se queda todo el tiempo en mi casa?","Depende de la modalidad. Una visita puntual no equivale a una estancia continua. Debes acordar duración, tareas y supervisión antes de contratar."]]},
 {slug:"entrenamiento-canino",name:"Entrenamiento canino",title:"Entrenamiento y educación canina en Colombia",description:"Conoce la propuesta de entrenamiento canino de Chomby: educación de cachorros, hábitos, paseos y elección de entrenador. Servicios por confirmar.",eyebrow:"APRENDER A CONVIVIR",intro:"Comprenderlo mejor también es una forma de cuidarlo.",definition:"El entrenamiento o educación canina acompaña el aprendizaje de hábitos y la convivencia entre el perro y su familia. Chomby contempla conectar con profesionales que expliquen su experiencia, método, objetivos y alcance antes de iniciar las sesiones.",sections:[
 {heading:"Educación de cachorros y hábitos cotidianos",text:"Puedes consultar por rutinas en casa, aprendizaje de señales básicas, paseos con correa o convivencia. Cada profesional deberá valorar el caso y proponer objetivos apropiados; no hay un número de sesiones ni resultados garantizados para todos los perros.",items:["Rutinas y educación de cachorros.","Paseo con correa y comunicación con el cuidador.","Hábitos para la convivencia en el hogar.","Orientación a la familia para practicar entre sesiones."]},
 {heading:"Cómo elegir un entrenador canino",text:"Pregunta cómo trabaja, qué experiencia tiene con situaciones similares y cómo involucra a la familia. Antes de contratar, acuerda objetivos, modalidad, duración de cada sesión y seguimiento. La propuesta de trabajo debe priorizar el bienestar animal."},
 {heading:"Entrenamiento, comportamiento y atención veterinaria",text:"Un entrenador no sustituye al veterinario. Si observas cambios de conducta o tienes dudas sobre la salud del animal, consulta con un profesional veterinario para decidir qué evaluación necesita. La disponibilidad de especialistas en comportamiento deberá confirmarse por separado."}
 ],compare:{title:"Preguntas para tu futuro entrenador",items:["¿Qué formación y experiencia tienes?","¿Qué métodos utilizas y cómo cuidas el bienestar del perro?","¿Cómo se definen los objetivos de las sesiones?","¿El servicio será individual, grupal, virtual o presencial?","¿Cuál es el precio y qué seguimiento incluye?"]},price:"El precio de entrenamiento canino se confirmará por profesional, sesión o programa. Chomby no anuncia paquetes, número de sesiones ni resultados garantizados en esta etapa.",coverage:"Las opciones presenciales dependerán de la ciudad y zona. No se ha confirmado entrenamiento a domicilio ni atención virtual de entrenadores en Chomby.",faqs:[
 ["¿Cuánto cuesta un entrenador de perros en Colombia?","No hay una tarifa única en Chomby. El profesional deberá indicar precio, modalidad, duración de cada sesión y alcance del acompañamiento."],
 ["¿Puedo buscar entrenamiento para un cachorro?","La categoría contempla educación de cachorros, sujeto a profesionales adecuados. El entrenador deberá revisar el caso y acordar objetivos con la familia."],
 ["¿Cuántas clases necesita mi perro?","No se puede fijar una cantidad igual para todos. El profesional deberá valorar necesidades, objetivos y participación de la familia antes de proponer un plan."],
 ["¿Habrá adiestramiento canino a domicilio?","La modalidad a domicilio no está confirmada. Deberá aparecer expresamente en el perfil del proveedor, con zona, horarios y condiciones."],
 ["¿Un entrenador puede diagnosticar un problema de salud?","El entrenamiento no reemplaza una valoración veterinaria. Las dudas sobre salud deben ser evaluadas por un veterinario, quien determinará si se requiere atención presencial u otro profesional."]]}
];
